# -*- coding: utf-8 -*-
"""List_dict_sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXhb6sSOfYHzvIN-D6rNAyOot_-6Dc-l

LISTS
"""

a=["apple","oranges","lemons"]

b=[1,2,0,"Riya",True]

d= "apple"
c= "oranges"
f="lemons"

if d == "apple":
  print(True)

if c=="apple":
  print(True)

len(a)

a.index("apple")

a.index("oranges")

"""SETS

"""

d= ["apples","apples","orange","lemon","orange"]

d

set(d)

first_set={1,3,4}

first_set

"""Dictionary

"""

a_1={"name":"Shloka",
     "age":23,
     "gender":"female",
     "status":True}

a_1["status"]

"""two dictionary in one list

"""

a_1=[{"name":"Shloka",
     "age":23,
     "gender":"female",
     "status":True},
      {"name":"Arjun",
       "age":"25",
       "gender":"male",
       "status":True}]

a_1[0]["name"]

a_1[1]["name"]

"""List Functions

"""

a

a.append("corn flakes")

a

a.append("momos")

a

a.remove('apple')

a

