# -*- coding: utf-8 -*-
"""Operations_on_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZIj2CMauobme1ftpFwIn6DrV-I0BC5-
"""

a=1

b=2

a+b

a-b

type(a-b)

type(a/b)

name=input()

print("Hi:"+ name)

c=4

d=2

c%d

items=[1,2,3,4]

for i in items:
  if i%2==0:
    print(i)

a*b

for i in items:
  if i/2==1:
    print(i)

print("Hi: "+input())

name = "Shloka"

name== "Ria"

a<1

a>b

a>=1

a<=1

10+4*(45-5)/5

name= "Shloka"
password= "Riya20"

check_username=input()
check_password= input()
if check_username== name and check_password== password:
  print("Hello:"+ name)
else:
    print("incorrect password")

check_username=input()
check_password= input()
if check_username== name or check_password== password:
  print("Hello:"+ name)
else:
    print("incorrect password")

check_username=input()
check_password= input()
if check_username== name and check_password== password:
  print("Hello:"+ name)
else:
    print("incorrect password")

check_username=input()
check_password= input()
if check_username== name and not check_password== password:
  print("Hello:"+ name)
else:
    print("incorrect password")

check_username=input()
check_password= input()
if check_username== name and not check_password== password:
  print("Hello:"+ name)
else:
    print("incorrect password")

a==6

if a==1:
 print(a+b)
else:
  print ("Its not true")

