# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCTZ03iMaFK6KlGukSkhWqjkEdAXmTFI
"""

Number_of_patients=2
type(Number_of_patients)

P1_name= "Shraddha"
type(P1_name)

P2_name= "Khushi"
type(P2_name)

P1_age= 22
str(P1_age)+ "years"

P2_age= 25
str(P2_age) + "years"

P1_weight= 57.4
str(P1_weight) + "kg"

P2_weight= 65.3
str(P2_weight) + "kg"

type(P1_weight)

type(P2_weight)

type(int(float(P1_weight)))

int(float(P1_weight))

type(int(float(P2_weight)))

int(float(P2_weight))

type(str(P1_age))

type(str(P2_age))

Both_girls=True

type(Both_girls)

