# -*- coding: utf-8 -*-
"""Variables_data_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DI6ygjOys4zJEzXCAYFjwwRXvLGcjPnj
"""

global a
a=1
type (a)

a=1.0
type(a)

b=2

a

b

a= "hi how are you"
type(a)

a

b=True
type(b)

b

type(a)

a=2

type(a)

float(a)

type(bool(a))

bool(a)

str(a)

type(a)

type(str(a))

"hi are you enjoying the class"+str(a)

type(int(float(a)))

int(float(a))

"""Naming convention"""

patient_age=42

d1=45

road=100

str(road)+"km"

